/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pipedream.ventanas;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pipedream.juego.Jugador;
import pipedream.juego.MejoresPuntajes;

/**
 *
 * @author Usuario
 */
public class VentPrincipal extends javax.swing.JFrame {

    private Jugador jugador = null;
    private MejoresPuntajes mp = null;
    private boolean existe = true;
    /**
     * Creates new form VentPrincipal
     */
    public VentPrincipal() {
        this.lookAndFeel();
        this.setTitle("PipeDream");
        initComponents();
        setLayout(new BorderLayout());
        JLabel background = new JLabel(new ImageIcon("/imagenes/fondo.png"));
        add(background);
        background.setLayout(new FlowLayout());
        
        
        //Centro pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        this.load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMaxPuntaciones = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        White = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setBackground(new java.awt.Color(255, 0, 102));
        btnJugar.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 204, 204));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, 50));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 102));
        btnCerrar.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 204, 204));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 50));

        btnMaxPuntaciones.setBackground(new java.awt.Color(255, 0, 102));
        btnMaxPuntaciones.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        btnMaxPuntaciones.setForeground(new java.awt.Color(255, 204, 204));
        btnMaxPuntaciones.setText("Maximas Puntuaciones");
        btnMaxPuntaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxPuntacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaxPuntaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 180, 50));

        btnInstrucciones.setBackground(new java.awt.Color(255, 0, 102));
        btnInstrucciones.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 204, 204));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 50));

        White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Sonriendo.gif"))); // NOI18N
        getContentPane().add(White, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(800, 600));
        fondo.setMinimumSize(new java.awt.Dimension(800, 600));
        fondo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        
         String nombre = JOptionPane.showInputDialog(this, "Cual es su nombre?", "Datos iniciales", JOptionPane.INFORMATION_MESSAGE);
        if(nombre != null){
            if(nombre.equals("")){
                nombre = "Jugador 1";
            }
            jugador = new Jugador(nombre);
            
            VentJuego ventana = new VentJuego(jugador, mp);

            ventana.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMaxPuntacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxPuntacionesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, mp.puntajes(), "Maximas Puntuaciones", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Sonriendo.gif")));
    }//GEN-LAST:event_btnMaxPuntacionesActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        // TODO add your handling code here:
        String str = "Bienvenido a PipeDream\n"
                + "El juego consiste en formar la unión de caños mas larga posible.\n"
                + "Si el agua se derrama, pierdes!  :(\n"
                + "Si el agua desemboca fuera del tablero, habrás ganado!  :)\n"
                + "Recuerda que malgastar caños será penalizado  :/\n"
                + "A DIVERTIRSE!!!";
        
        JOptionPane.showMessageDialog(this, str, "Instrucciones - Hecho por Francisco Bartolomé y José Vitali", JOptionPane.INFORMATION_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Explicando.gif")));
        
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    private void lookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    private void load(){
        try
        {
            FileInputStream fileIn;
            fileIn = new FileInputStream("puntajes.pd");
            ObjectInputStream in;
            in = new ObjectInputStream(fileIn);
            mp = (MejoresPuntajes) in.readObject();
            in.close();
            fileIn.close();
        }catch(IOException | ClassNotFoundException e)
        {
            existe = false;
        }
        if(existe == false){
            mp = new MejoresPuntajes();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel White;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnMaxPuntaciones;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
