/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pipedream.ventanas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import pipedream.canios.Canio;
import pipedream.juego.Juego;
import pipedream.juego.Juego.EstadoDeJuego;
import pipedream.juego.Jugada;
import pipedream.juego.Jugador;
import pipedream.juego.Listener;
import pipedream.juego.MejoresPuntajes;

/**
 *
 * @author Francisco
 */
public class VentJuego extends javax.swing.JFrame implements Listener{
    
    private static final int SIZE = 50;

    /**
     * Creates new form VentJuego
     */
    
    private final Matriz matriz;
    private final JLabel colaCanios[];
    private final Jugador jugador;
    private final Juego juego;
    private Canio canios[];
    private final Imagenes imagenes;
    
    public VentJuego(Jugador jugador, MejoresPuntajes mp) {
        this.lookAndFeel();
        this.setTitle("PipeDream");
        initComponents();
        
        imagenes = new Imagenes();
        
        jPanel3.setLayout(new BorderLayout());
        jPanel4.setLayout(new BorderLayout());
        jPanel5.setLayout(new BorderLayout());
        jPanel6.setLayout(new BorderLayout());
        jPanel7.setLayout(new BorderLayout());
        
        jPanel3.add(jLabel2, BorderLayout.CENTER);
        jPanel4.add(jLabel3, BorderLayout.CENTER);
        jPanel5.add(jLabel4, BorderLayout.CENTER);
        jPanel6.add(jLabel5, BorderLayout.CENTER);
        jPanel7.add(jLabel6, BorderLayout.CENTER);
        
        jPanel3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.WHITE));
                
        LabelPausa.setVisible(false);
        
        //Centro pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        matriz = new Matriz();
        llenarMatriz();
        
        colaCanios = new JLabel[5];
        
        colaCanios[0] = jLabel2;
        colaCanios[1] = jLabel3;
        colaCanios[2] = jLabel4;
        colaCanios[3] = jLabel5;
        colaCanios[4] = jLabel6;
        
        
        
        this.jugador = jugador;
        
        
        
        juego = new Juego(jugador, mp, this);
        juego.jugar();
        
        canios = new Canio[5];
        
        
        llenarColaCanios();
        

    }    
    
    private  void llenarMatriz(){
        
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                JPanel casillero = new JPanel();
                casillero.setBorder(BorderFactory.createLineBorder(Color.WHITE));
                casillero.setSize(SIZE, SIZE);
                JLabel jLabel = new JLabel();
               
                if(i == 0 && j == 0){
                    jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CanioHorizontalIZQUIERDA1.png")));
                }
                else
                    jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nada.png")));
                
                matriz.addLabel(j, i, jLabel);
                casillero.addMouseListener(new MyMouseAdapter(this, j, i));
                tablero.setLayout(null);
                tablero.add(casillero);
                
                
                casillero.setLocation(i * SIZE, j * SIZE);
                
                casillero.setLayout(new BorderLayout());
                casillero.add(jLabel, BorderLayout.CENTER);
            }
        }
    }
    
    public void casilleroMouseClicked(java.awt.event.MouseEvent evt, int i, int j) {                                     
        // TODO add your handling code here:
        if(!juego.getPausa()){
            if(juego.agregarCanio(i, j))
                llenarColaCanios();
            setImage(i,j);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finDelJuego = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LabelPausa = new javax.swing.JLabel();
        tablero = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnAcelerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        finDelJuego.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout finDelJuegoLayout = new javax.swing.GroupLayout(finDelJuego.getContentPane());
        finDelJuego.getContentPane().setLayout(finDelJuegoLayout);
        finDelJuegoLayout.setHorizontalGroup(
            finDelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        finDelJuegoLayout.setVerticalGroup(
            finDelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta, 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 244, 54, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta, 2));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 300, 54, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta, 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 356, 54, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta, 2));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 412, 54, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta, 2));
        jPanel7.setFocusable(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 468, 54, -1));

        LabelPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Pausa.gif"))); // NOI18N
        getContentPane().add(LabelPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 204, -1, -1));

        tablero.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.magenta));

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        getContentPane().add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 500, 500));

        btnSalir.setBackground(new java.awt.Color(255, 0, 102));
        btnSalir.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 30));

        btnPausa.setBackground(new java.awt.Color(255, 0, 102));
        btnPausa.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPausa.setText("Pausa");
        btnPausa.setToolTipText("");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 32));

        btnAcelerar.setBackground(new java.awt.Color(102, 204, 255));
        btnAcelerar.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnAcelerar.setForeground(new java.awt.Color(0, 0, 204));
        btnAcelerar.setText("Acelerar");
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        // TODO add your handling code here:
        if(!juego.getPausa())
            juego.apurar();
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        // TODO add your handling code here:
        juego.pausar();
        if(juego.getPausa())
            LabelPausa.setVisible(true);
        else
            LabelPausa.setVisible(false);
    }//GEN-LAST:event_btnPausaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
            juego.salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lookAndFeel(){
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPausa;
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDialog finDelJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notifyOfThreadComplete() {
        if(juego.getEstado() != EstadoDeJuego.SALIO){
            JOptionPane.showMessageDialog(this, (juego.getEstado() == EstadoDeJuego.GANO) ? "Fantástico!!\nHas logrado " + jugador.getPuntaje() + " puntos": "Has sido derrotado...", "Termino el juego", JOptionPane.INFORMATION_MESSAGE,
                    (juego.getEstado() == EstadoDeJuego.GANO) ? new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Luciendose.gif")) 
                            : new javax.swing.ImageIcon(getClass().getResource("/imagenes/White_Perdio.gif")));
        }
        VentPrincipal ventanaPrincipal = new VentPrincipal();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }

    @Override
    public void changeImage(Jugada jugada) {
       setImage(jugada.getX(), jugada.getY());
    }
    
    public void setImage(int x, int y){
        JLabel jLabel = matriz.getLabel(x, y);
        Canio canio = juego.getTablero().getTablero()[x][y];
        
        String dir;
        if(canio == null)
            dir = "/imagenes/" + "Nada" + ".png";
        else
            dir = "/imagenes/" + "Canio" + canio + ".png";
            
        jLabel.setIcon(imagenes.getImagen(dir));
        
        
    }
    
    private void llenarColaCanios(){
        canios = (juego.getCola().toArray(canios));
        for (int i = 0; i < 5; i++) {
            String dir = "/imagenes/Canio" + canios[i] + ".png";
            
            colaCanios[i].setIcon(imagenes.getImagen(dir));
        }
    }
}
